ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "signs up admin account and makes endeavors"
task :make_admin do
    admin = User.create(username: "admin", password:"password") 
    admin.endeavors << Endeavor.create(title: "My trip to Paris", description: "Im gonna miss this trip! So much fun roaming the streets and we actually got to go inside the catacombs. It was insane down there and it was so scary. At one point Mark, Gerald, Arzy and I deviated from the tour group and we got lost! We were roaming throough the catacombs like we were in a corn maze! Although it sounds fun in retrospect, it was actually really scary in the moment. Unforgettable experience. Drinking the next day was even better. Loved it. Need to do it again sometime.", pic: "https://www.dropbox.com/s/nnjszpmxnhoq38f/eiffel.jpg?raw=1", pic_caption: "Here's a picture of the eiffel tower. That's where we were!")
    admin.endeavors << Endeavor.create(status:"completed",title:"Arzy Takes on Europe",description:"Backpacking through Europe! Amazing experience! It was so contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",pic:"https://www.dropbox.com/s/g5lsaw111r361wn/leaningtowerofpizza.jpg?raw=1",pic_caption:"me and bae with our backpacks in front of the leaning tower of pizza")
    admin.endeavors << Endeavor.create(status:"completed",title:"Snowboarding in Aspen",description:"When it comes time to try on your snowboard, the first thing you will need to do is determine your “stance.” Your stance is the direction you face while sliding downhill. There are two snowboard stances, regular and goofy. A regular stance means that your left foot is forward, while a goofy stance means that your right foot it forward. There is no correct snowboard stance, it is all about what feels good to you.",pic:"https://www.dropbox.com/s/mbuaiu2p6l0kuzb/snowboarding-aspen.jpg?raw=1",pic_caption:"Shredding that POW was so gnarly!")
    admin.endeavors << Endeavor.create(status:"completed",title:"Cliffjumping at Devils Hole",description:"Check out how deep the water is. You can do that by engaging in a little research on that particular river or lake or simply ask someone that can help you with this information. If you happen to be out in the wild and are in a situation when you have to jump- this is a movie-like scenario, but you never know-, here’s an interesting solution you could try: find some natural vegetation that could be used as a rope, tie it together and then tie a rock at the end of it. This way, by throwing the rock in the water, you will know approximatively how deep it is. If it is less than 4 meters, then it is not safe, so you should search for alternatives. Also, be aware of the tides in the area. If you are a good swimmer, you can try twisting in order to escape the currents.",pic:"https://www.dropbox.com/s/fps8znwu0jkwrxo/cliffjumping-devilshole.jpg?raw=1",pic_caption:"This was the jump we were doing!")
    admin.endeavors << Endeavor.create(status:"completed",title:"Glamping in a Tipi",description:"Glamping is where stunning nature meets modern luxury. It’s a way to experience the untamed and completely unique parts of the world—without having to sacrifice creature comforts.The way we travel has changed. We no longer want a generic, one-size-fits-all vacation. We want to explore on our terms and immerse ourselves in local culture, and we no longer just want to simply witness nature—we want to live in it. A fusion of glamour and camping, glamping is a way to authentically experience the most awe-inspiring locales around the world.",pic:"https://www.dropbox.com/s/ao915zt7txmga3r/glamping-tipi.jpg?raw=1",pic_caption:"The tipi we stayed in!")
    admin.endeavors << Endeavor.create(title:"To the Moooooon",description:"We went to the mueseum! I saw alot of cool artifacts! Alot of precious things where spotted on the moon actually. And there were even some artifacts that astronauts themselves brought back. One of the strangest artifacts that was brought back from the moon was by Astronaut Melvin and it was a game-disc. Something you would usually buy at GameStop. ",pic:"https://www.dropbox.com/s/4tno8a5u24zgud1/gamestonk.webp?raw=1",pic_caption:"TO THE MOOOOOON!")
    admin.endeavors << Endeavor.create(title:"A dog on the moon!",description:"We went to the mueseum once again! This time we saw a picture that was taking by Astronaut Elon! It was a picture of a Doge on the moon! Oh sorry typo, I meant to say Dog! It was an actualy Dog on the Moon! Who wouldve thought right? Anyways, heres the picture of the picture that Astronaut Elon Musk himself took.",pic:"https://www.dropbox.com/s/tlm151yo5fnx4kt/dogecoin.webp?raw=1",pic_caption:"HERES THE DOGE ON THE MOON! oh sorry, dog**")
    admin.endeavors << Endeavor.create(title:"Magic in the Hamptons",description:"You know where I go when we're dancing Handshakes in The Hamptons And gettin' drunk in the mansions with you And you look so classy Come through with that magic You know that I'm 'bout to smash it, it's true",pic:"https://www.dropbox.com/s/ohcssd7izy2kw3a/baronscove.jpg?raw=1",pic_caption:"Barons Cove in Sag Harbor, shout out to Mario")
end
